### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ZhiyuanChen** [byrnereese/mkdocs-git-committers-plugin#8]
ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zc\\AppData\\Local\\Temp\\pip-install-sptzmlzr\\mkdocs-git-committers-plugin\\setup.py'"'"'; __file__='"'"'C:\\Users\\zc\\AppData\\Local\\Temp\\pip-install-sptzmlzr\\mkdocs-git-committers-plugin\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\zc\AppData\Local\Temp\pip-install-sptzmlzr\mkdocs-git-committers-plugin\
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\__init__.py", line 228, in <module>
        monkey.patch_all()
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\monkey.py", line 101, in patch_all
        patch_for_msvc_specialized_compiler()
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\monkey.py", line 138, in patch_for_msvc_specialized_compiler
        msvc = import_module('setuptools.msvc')
      File "c:\programdata\anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\msvc.py", line 58, in <module>
        from distutils.msvc9compiler import Reg
      File "c:\programdata\anaconda3\lib\distutils\msvc9compiler.py", line 254
        def query_vcvarsall(versvc_env ion, arch="x86"):
                                         ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

OS: Windows 10
conda version : 4.7.11
conda-build version : 3.18.9
python version : 3.6.8.final.0

**Comment by GeckoEidechse** [comment]
This could probably be closed as _stale_ given the age of this issue.
